name: Build Android APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Backup user code
        run: |
          mkdir -p ../temp_code
          cp lib/main.dart ../temp_code/main.dart

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Re-create Clean Flutter Project
        run: |
          cd ..
          rm -rf $GITHUB_WORKSPACE/*
          flutter create --org com.example --project-name adhyayan $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          cp ../temp_code/main.dart lib/main.dart

      - name: Update Android App Label to Bangla
        run: |
          sed -i 's/android:label="adhyayan"/android:label="অধ্যয়ন"/g' android/app/src/main/AndroidManifest.xml

      - name: Install Dependencies
        run: |
          flutter pub add webview_flutter

      - name: Build Release APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
